# Generated by Django 5.0 on 2023-12-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_explicamisto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
