# Generated by Django 5.0 on 2023-12-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_explicamisto', '0003_user_telephone1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telephone1',
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(choices=[('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2),
        ),
    ]
