# Generated by Django 5.0 on 2023-12-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_explicamisto', '0006_alter_scholar_info_year1'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.TextField(blank=True, max_length=100)),
                ('district', models.CharField(choices=[('Aveiro', 1), ('Beja', 2), ('Braga', 3), ('Bragança', 4), ('Castelo Branco', 5), ('Coimbra', 6), ('Évora', 7), ('Faro', 8), ('Guarda', 9), ('Leiria', 10), ('Lisboa', 11), ('Portalegre', 12), ('Porto', 13), ('Santarém', 14), ('Setúbal', 15), ('Viana do Castelo', 16), ('Vila Real', 17), ('Viseu', 18), ('Madeira', 19), ('Açores', 20)], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='scholar_info',
        ),
    ]
