# Generated by Django 5.0 on 2023-12-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_explicamisto', '0011_explicador_aluno_delete_school_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('explicador', 'Explicador')], default='', max_length=20),
        ),
    ]
