# Generated by Django 5.0 on 2023-12-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_explicamisto', '0013_explicador_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explicador',
            name='ciclo_de_estudos',
            field=models.CharField(choices=[('1', 'licenciatura'), ('2', 'mestrado')], default='', max_length=15),
        ),
    ]
