# Generated by Django 5.0 on 2023-12-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_explicamisto', '0020_explicador_número_de_horas_disponíveis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nota_primeiro_teste',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
